set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_rst_ps8_0_99M_0/kr260_bd_rst_ps8_0_99M_0.xdc rfile:../../../vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_rst_ps8_0_99M_0/kr260_bd_rst_ps8_0_99M_0.xdc id:1 order:EARLY scoped_inst:kr260_bd_i/rst_ps8_0_99M/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_axi_smc_0/bd_0/ip/ip_1/bd_ac08_psr_aclk_0.xdc rfile:../../../vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_axi_smc_0/bd_0/ip/ip_1/bd_ac08_psr_aclk_0.xdc id:2 order:EARLY scoped_inst:kr260_bd_i/axi_smc/inst/clk_map/psr_aclk/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_proc_sys_reset_1_0/kr260_bd_proc_sys_reset_1_0.xdc rfile:../../../vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_proc_sys_reset_1_0/kr260_bd_proc_sys_reset_1_0.xdc id:3 order:EARLY scoped_inst:kr260_bd_i/proc_sys_reset_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_proc_sys_reset_0_0/kr260_bd_proc_sys_reset_0_0.xdc rfile:../../../vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_proc_sys_reset_0_0/kr260_bd_proc_sys_reset_0_0.xdc id:4 order:EARLY scoped_inst:kr260_bd_i/proc_sys_reset_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_clk_wiz_0_0/kr260_bd_clk_wiz_0_0.xdc rfile:../../../vMotion.gen/sources_1/bd/kr260_bd/ip/kr260_bd_clk_wiz_0_0/kr260_bd_clk_wiz_0_0.xdc id:5 order:EARLY scoped_inst:kr260_bd_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.srcs/constrs_1/new/fan_pinout.xdc rfile:../../../vMotion.srcs/constrs_1/new/fan_pinout.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.srcs/constrs_1/new/pmod_pinout.xdc rfile:../../../vMotion.srcs/constrs_1/new/pmod_pinout.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:/home/juan/Desktop/ws/portfolio/vision-based-motion-control/firmware/fpga/vMotion/vMotion.srcs/constrs_1/new/rpi_pinout.xdc rfile:../../../vMotion.srcs/constrs_1/new/rpi_pinout.xdc id:8} [current_design]
current_instance kr260_bd_i/rst_ps8_0_99M/U0
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_bd_i/axi_smc/inst/clk_map/psr_aclk/U0
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_bd_i/proc_sys_reset_1/U0
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_bd_i/proc_sys_reset_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance kr260_bd_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {fan_en_b}]
set_property src_info {type:XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {pmod1_io[0]}]
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {pmod1_io[1]}]
set_property src_info {type:XDC file:7 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {pmod1_io[2]}]
set_property src_info {type:XDC file:7 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports {pmod1_io[3]}]
set_property src_info {type:XDC file:7 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {pmod1_io[4]}]
set_property src_info {type:XDC file:7 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {pmod1_io[5]}]
set_property src_info {type:XDC file:7 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {pmod1_io[6]}]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports {pmod1_io[7]}]
set_property src_info {type:XDC file:7 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports {pmod2_io[0]}]
set_property src_info {type:XDC file:7 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports {pmod2_io[1]}]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {pmod2_io[2]}]
set_property src_info {type:XDC file:7 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {pmod2_io[3]}]
set_property src_info {type:XDC file:7 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {pmod2_io[4]}]
set_property src_info {type:XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {pmod2_io[5]}]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {pmod2_io[6]}]
set_property src_info {type:XDC file:7 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports {pmod2_io[7]}]
set_property src_info {type:XDC file:7 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12 [get_ports {pmod3_io[0]}]
set_property src_info {type:XDC file:7 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {pmod3_io[1]}]
set_property src_info {type:XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10 [get_ports {pmod3_io[2]}]
set_property src_info {type:XDC file:7 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH10 [get_ports {pmod3_io[3]}]
set_property src_info {type:XDC file:7 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11 [get_ports {pmod3_io[4]}]
set_property src_info {type:XDC file:7 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11 [get_ports {pmod3_io[5]}]
set_property src_info {type:XDC file:7 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12 [get_ports {pmod3_io[6]}]
set_property src_info {type:XDC file:7 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11 [get_ports {pmod3_io[7]}]
set_property src_info {type:XDC file:7 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC12 [get_ports {pmod4_io[0]}]
set_property src_info {type:XDC file:7 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports {pmod4_io[1]}]
set_property src_info {type:XDC file:7 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10 [get_ports {pmod4_io[2]}]
set_property src_info {type:XDC file:7 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports {pmod4_io[3]}]
set_property src_info {type:XDC file:7 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports {pmod4_io[4]}]
set_property src_info {type:XDC file:7 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10 [get_ports {pmod4_io[5]}]
set_property src_info {type:XDC file:7 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports {pmod4_io[6]}]
set_property src_info {type:XDC file:7 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports {pmod4_io[7]}]
set_property src_info {type:XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {rpi_gpio[0]}]
set_property src_info {type:XDC file:8 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD14 [get_ports {rpi_gpio[1]}]
set_property src_info {type:XDC file:8 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {rpi_gpio[2]}]
set_property src_info {type:XDC file:8 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE14 [get_ports {rpi_gpio[3]}]
set_property src_info {type:XDC file:8 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {rpi_gpio[4]}]
set_property src_info {type:XDC file:8 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {rpi_gpio[5]}]
set_property src_info {type:XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG13 [get_ports {rpi_gpio[6]}]
set_property src_info {type:XDC file:8 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports {rpi_gpio[7]}]
set_property src_info {type:XDC file:8 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports {rpi_gpio[8]}]
set_property src_info {type:XDC file:8 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports {rpi_gpio[9]}]
set_property src_info {type:XDC file:8 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {rpi_gpio[10]}]
set_property src_info {type:XDC file:8 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {rpi_gpio[11]}]
set_property src_info {type:XDC file:8 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {rpi_gpio[12]}]
set_property src_info {type:XDC file:8 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13 [get_ports {rpi_gpio[13]}]
set_property src_info {type:XDC file:8 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {rpi_gpio[14]}]
set_property src_info {type:XDC file:8 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {rpi_gpio[15]}]
set_property src_info {type:XDC file:8 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {rpi_gpio[16]}]
set_property src_info {type:XDC file:8 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {rpi_gpio[17]}]
set_property src_info {type:XDC file:8 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {rpi_gpio[18]}]
set_property src_info {type:XDC file:8 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {rpi_gpio[19]}]
set_property src_info {type:XDC file:8 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W12 [get_ports {rpi_gpio[20]}]
set_property src_info {type:XDC file:8 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11 [get_ports {rpi_gpio[21]}]
set_property src_info {type:XDC file:8 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports {rpi_gpio[22]}]
set_property src_info {type:XDC file:8 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports {rpi_gpio[23]}]
set_property src_info {type:XDC file:8 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {rpi_gpio[24]}]
set_property src_info {type:XDC file:8 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {rpi_gpio[25]}]
set_property src_info {type:XDC file:8 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {rpi_gpio[26]}]
set_property src_info {type:XDC file:8 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {rpi_gpio[27]}]
